-- Day 5 schema for TrackMyLife weekly priorities
-- Run this in Supabase SQL Editor once. Safe to re-run (idempotent).

create table if not exists public.weekly_priorities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null,
  priority text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start)
);

alter table public.weekly_priorities enable row level security;

-- Reuses public.set_updated_at() defined in day3_daily_entries.sql.
drop trigger if exists set_weekly_priorities_updated_at on public.weekly_priorities;
create trigger set_weekly_priorities_updated_at
before update on public.weekly_priorities
for each row
execute function public.set_updated_at();

drop policy if exists "weekly_priorities_select_own" on public.weekly_priorities;
create policy "weekly_priorities_select_own"
on public.weekly_priorities
for select
using (auth.uid() = user_id);

drop policy if exists "weekly_priorities_insert_own" on public.weekly_priorities;
create policy "weekly_priorities_insert_own"
on public.weekly_priorities
for insert
with check (auth.uid() = user_id);

drop policy if exists "weekly_priorities_update_own" on public.weekly_priorities;
create policy "weekly_priorities_update_own"
on public.weekly_priorities
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "weekly_priorities_delete_own" on public.weekly_priorities;
create policy "weekly_priorities_delete_own"
on public.weekly_priorities
for delete
using (auth.uid() = user_id);

-- Per-day update on the active weekly priority, stored alongside the daily note.
alter table public.daily_entries add column if not exists priority_update text;
