-- Day 8 schema for TrackMyLife custom metrics
-- Run this in Supabase SQL Editor once. Safe to re-run (idempotent).
--
-- Additive feature: the built-in bedtime/instagram columns on daily_entries are
-- untouched. Custom metrics live in their own two tables alongside them.
--
--   metric_definitions  -- a user's catalog of custom metrics (max 2 active)
--   metric_values       -- one numeric value per metric per day
--
-- v1 supports kind = 'number' | 'duration' only. Both store a plain numeric;
-- they differ only in how the value is formatted for display. Time-of-day is
-- future scope: it is cyclic and needs a per-metric anchor (see the bedtime
-- lateness math in dashboard-helpers.ts), so it is intentionally not a kind here.

-- ---------------------------------------------------------------------------
-- metric_definitions
-- ---------------------------------------------------------------------------
create table if not exists public.metric_definitions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  unit text,
  kind text not null default 'number' check (kind in ('number', 'duration')),
  is_public boolean not null default false,
  sort_order smallint not null default 0,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.metric_definitions enable row level security;

-- Case-insensitive uniqueness among a user's ACTIVE metrics only, so archiving
-- "Water" and creating a fresh "Water" later does not collide.
drop index if exists metric_definitions_active_name_unique;
create unique index metric_definitions_active_name_unique
  on public.metric_definitions (user_id, lower(name))
  where archived = false;

-- Reuses public.set_updated_at() defined in day3_daily_entries.sql.
drop trigger if exists set_metric_definitions_updated_at on public.metric_definitions;
create trigger set_metric_definitions_updated_at
before update on public.metric_definitions
for each row
execute function public.set_updated_at();

-- Authoritative cap: at most 2 ACTIVE custom metrics per user. Enforced in the
-- database so an app bug can never exceed it. The UI should also disable "Add"
-- at 2, but this is the real guard.
create or replace function public.enforce_metric_definitions_cap()
returns trigger
language plpgsql
as $$
declare
  active_count integer;
begin
  if new.archived = false then
    select count(*) into active_count
    from public.metric_definitions
    where user_id = new.user_id
      and archived = false
      and id is distinct from new.id;  -- exclude the row being un-archived/updated
    if active_count >= 2 then
      raise exception 'metric cap reached: a user may have at most 2 active custom metrics';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_metric_definitions_cap on public.metric_definitions;
create trigger enforce_metric_definitions_cap
before insert or update on public.metric_definitions
for each row
execute function public.enforce_metric_definitions_cap();

drop policy if exists "metric_definitions_select_own" on public.metric_definitions;
create policy "metric_definitions_select_own"
on public.metric_definitions
for select
using (auth.uid() = user_id);

drop policy if exists "metric_definitions_insert_own" on public.metric_definitions;
create policy "metric_definitions_insert_own"
on public.metric_definitions
for insert
with check (auth.uid() = user_id);

drop policy if exists "metric_definitions_update_own" on public.metric_definitions;
create policy "metric_definitions_update_own"
on public.metric_definitions
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "metric_definitions_delete_own" on public.metric_definitions;
create policy "metric_definitions_delete_own"
on public.metric_definitions
for delete
using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- metric_values
-- ---------------------------------------------------------------------------
create table if not exists public.metric_values (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  metric_id bigint not null references public.metric_definitions(id) on delete cascade,
  entry_date date not null,
  value numeric not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, metric_id, entry_date)
);

alter table public.metric_values enable row level security;

-- Fast lookup of a user's values within a date window for a metric.
create index if not exists metric_values_user_metric_date_idx
  on public.metric_values (user_id, metric_id, entry_date);

drop trigger if exists set_metric_values_updated_at on public.metric_values;
create trigger set_metric_values_updated_at
before update on public.metric_values
for each row
execute function public.set_updated_at();

drop policy if exists "metric_values_select_own" on public.metric_values;
create policy "metric_values_select_own"
on public.metric_values
for select
using (auth.uid() = user_id);

drop policy if exists "metric_values_insert_own" on public.metric_values;
create policy "metric_values_insert_own"
on public.metric_values
for insert
with check (auth.uid() = user_id);

drop policy if exists "metric_values_update_own" on public.metric_values;
create policy "metric_values_update_own"
on public.metric_values
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "metric_values_delete_own" on public.metric_values;
create policy "metric_values_delete_own"
on public.metric_values
for delete
using (auth.uid() = user_id);
